// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBlWhi5XCtlRIS3VoO2JVdPa_TAp-w9fE',
    appId: '1:380875765645:web:876d61dec0533029586fc4',
    messagingSenderId: '380875765645',
    projectId: 'todos-44b6b',
    authDomain: 'todos-44b6b.firebaseapp.com',
    storageBucket: 'todos-44b6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAna6u3_1bQt7P-llPpXdCT4cUwKvtW9_g',
    appId: '1:380875765645:android:7958f8dbd8464fc7586fc4',
    messagingSenderId: '380875765645',
    projectId: 'todos-44b6b',
    storageBucket: 'todos-44b6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGtf7uxfBra11t3Y1ssDjryXmnxatfsOY',
    appId: '1:380875765645:ios:0548993d0586d55e586fc4',
    messagingSenderId: '380875765645',
    projectId: 'todos-44b6b',
    storageBucket: 'todos-44b6b.appspot.com',
    androidClientId: '380875765645-9pfq1qkqqt7irmkr9rkfo70fh80gr2f4.apps.googleusercontent.com',
    iosClientId: '380875765645-0ad8agst12e0i7p6lnkbn5h2qgo4m0lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeGaby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGtf7uxfBra11t3Y1ssDjryXmnxatfsOY',
    appId: '1:380875765645:ios:0548993d0586d55e586fc4',
    messagingSenderId: '380875765645',
    projectId: 'todos-44b6b',
    storageBucket: 'todos-44b6b.appspot.com',
    androidClientId: '380875765645-9pfq1qkqqt7irmkr9rkfo70fh80gr2f4.apps.googleusercontent.com',
    iosClientId: '380875765645-0ad8agst12e0i7p6lnkbn5h2qgo4m0lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.testeGaby',
  );
}
